# Generated by Django 3.2.19 on 2023-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_county',
            field=models.CharField(blank=True, choices=[('Greater London', 'Greater London'), ('Greater Manchester', 'Greater Manchester'), ('West Midlands', 'West Midlands'), ('West Yorkshire', 'West Yorkshire'), ('Merseyside', 'Merseyside'), ('Tyne and Wear', 'Tyne and Wear'), ('South Yorkshire', 'South Yorkshire'), ('Bristol', 'Bristol'), ('Nottinghamshire', 'Nottinghamshire'), ('Leicestershire', 'Leicestershire'), ('Hampshire', 'Hampshire'), ('Hampshire', 'Hampshire'), ('Oxfordshire', 'Oxfordshire'), ('Cambridgeshire', 'Cambridgeshire'), ('North Yorkshire', 'North Yorkshire'), ('East Sussex', 'East Sussex'), ('Somerset', 'Somerset'), ('West Midlands', 'West Midlands'), ('Staffordshire', 'Staffordshire'), ('Devon', 'Devon')], max_length=80, null=True),
        ),
    ]
